services:
  server:
    # image: 423623864913.dkr.ecr.eu-north-1.amazonaws.com/web-app/server:latest
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: bookstore_server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@db:5432/bookstore
    depends_on:
      - db
    networks:
      - bookstore_network

  db:
    image: postgres:13-alpine
    restart: always
    container_name: bookstore_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - bookstore_network

  client:
    # image: 423623864913.dkr.ecr.eu-north-1.amazonaws.com/web-app/client:latest
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: bookstore_client
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - server
    networks:
      - bookstore_network

  nginx:
    # image: 423623864913.dkr.ecr.eu-north-1.amazonaws.com/web-app/nginx:latest
    restart: always
    depends_on:
      - server
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: bookstore_nginx
    ports:
      - 8080:80
    networks:
      - bookstore_network

  node-exporter:
    restart: always
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    networks:
      - bookstore_network

  prometheus:
    restart: always
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bookstore_network
    depends_on:
      - node-exporter

  grafana:
    restart: always
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - bookstore_network
    depends_on:
      - prometheus

networks:
  bookstore_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
