services:
  server:
    image: 423623864913.dkr.ecr.eu-north-1.amazonaws.com/web-app/server:latest
    restart: always
    container_name: bookstore_server
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@db:5432/bookstore
    depends_on:
      - db
    networks:
      - bookstore_network

  db:
    image: postgres:13-alpine
    restart: always
    container_name: bookstore_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - bookstore_network

  client:
    image: 423623864913.dkr.ecr.eu-north-1.amazonaws.com/web-app/client:latest
    restart: always
    container_name: bookstore_client
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
    depends_on:
      - server
    networks:
      - bookstore_network

  nginx:
    image: 423623864913.dkr.ecr.eu-north-1.amazonaws.com/web-app/nginx:latest
    restart: always
    depends_on:
      - server
      - client
    container_name: bookstore_nginx
    ports:
      - 8080:80
    networks:
      - bookstore_network

networks:
  bookstore_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
