version: '3.9'

services:
  server:
    restart: always
    image: 423623864913.dkr.ecr.eu-north-1.amazonaws.com/web-app/server
    container_name: bookstore_server
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@db:5432/bookstore
    depends_on:
      - db
    networks:
      - bookstore_network

  db:
    image: postgres:13-alpine
    restart: always
    container_name: bookstore_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - bookstore_network

  client:
    restart: always
    image: 423623864913.dkr.ecr.eu-north-1.amazonaws.com/web-app/client
    container_name: bookstore_client
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - bookstore_network

  nginx:
    restart: always
    depends_on:
      - server
      - client
    image: 423623864913.dkr.ecr.eu-north-1.amazonaws.com/web-app/nginx
    container_name: bookstore_nginx
    ports:
      - 8080:80
    networks:
      - bookstore_network

networks:
  bookstore_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
